version: "3.9"

services:
  web:
    build: .
    container_name: nextjs_app
    env_file:
      - .env
    network_mode: "host"     # usa la red del host: localhost dentro del contenedor = localhost del host
    mem_limit: 1536m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
