version: "3.9"

services:
  web:
    build: .
    container_name: nextjs_app
    restart: unless-stopped
    env_file:
      - .env
    # Con host networking el contenedor usa la red del host (localhost = host)
    network_mode: "host"
    mem_limit: 1536m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
