ALTER TABLE `VoucherPagos`
  ADD COLUMN `retencionFuenteISR` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `retencionIHSS` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `retencionRAP` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `impuestoPersonalMunicipal` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `deduccionAnticipoSalario` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `totalDeducciones` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `reembolsos` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `retroactivoSM` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `bonos` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `feriados` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `metodoPago` VARCHAR(100) NOT NULL DEFAULT '';
